# Generated by Django 4.2.4 on 2023-09-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked_by_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
