# Generated by Django 4.2.4 on 2023-11-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_to_photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, max_length=300, null=True)),
                ('date_and_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('relation_to_photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
            ],
        ),
    ]
